name: Update Data

on:
  workflow_dispatch:
  push:
  schedule:
    # Run 4 times a day (every 6 hours)
    # At minute 17 past hour 0, 6, 12, and 18
    # https://crontab.guru/#17_6,18_*_*_*
    - cron: '17 0,6,12,18 * * *'
jobs:
  update:
    permissions:
      contents: write
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - name: Cache Unshorten
      uses: actions/cache@v4
      with:
        path: .cache.pkl
        key: "cache-unshorten-${{ github.run_id }}"
        restore-keys: "cache-unshorten-"
    - name: Cache Requests SQlite
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache/event-fetcher-cache.sqlite
        key: "cache-requests-${{ github.run_id }}"
        restore-keys: "cache-requests-"
    - uses: actions/checkout@v4
      name: Clone self repository
      with:
        ref: ${{ github.head_ref }}
    - name: Install curl-impersonate
      run: |
        sudo apt-get install -y libnss3 nss-plugin-pem ca-certificates
        wget "https://github.com/lwthiker/curl-impersonate/releases/download/v0.6.1/curl-impersonate-v0.6.1.x86_64-linux-gnu.tar.gz" -O /tmp/curl-impersonate.tar.gz
        echo "fa1e1614f7ba69ccc66721a0f38be457a3647eb64c75d66974b56186e3316b12  /tmp/curl-impersonate.tar.gz" | sha256sum --check --status
        sudo tar -xzf /tmp/curl-impersonate.tar.gz -C /usr/bin
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Setup
      run: |
        git config --global init.defaultBranch main
        git config --global extensions.partialClone true
        pip install -r requirements.txt
    - name: Fetch updates
      run: rm -rf out/* && make all && make db
      env:
        MELLO_JWT_TOKEN: ${{ secrets.MELLO_JWT_TOKEN }}
        ZOMATO_PUBLIC_API_KEY: ${{ secrets.ZOMATO_PUBLIC_API_KEY }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      id: upload
      with:
        name: events.db
        path: events.db
        if-no-files-found: error
        retention-days: 90

    - uses: stefanzweifel/git-auto-commit-action@v5
      name: Commit
      with:
        commit_message: |
          Automatic Updates 🤖
          
          Database URL: ${{ steps.upload.outputs.artifact-url }}
          Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/workflow
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        add_options: "--ignore-removal --update"
        file_pattern: "out/*"
        status_options: '--untracked-files=no'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}